### ISSUE TITLE
Hosted Blazor SPA Sample?

### ISSUE THREAD

**Issue by Webreaper** [danroth27/Net8BlazorWebAssembly#1]
I thought this was the sample I was looking for, but I think it's plain WebAssembly Blazor. Do you have an example of a hosted Blazor SPA conversion to use the new features?

If I'm misreading it, happy to be corrected. I'm looking at this commit https://github.com/danroth27/Net8BlazorWebAssembly/commit/44cf65ef602e89a5ec88b42d2f30f70d8f9fbda9 but I don't have a Host.razor in my app....

**Comment by danroth27** [comment]
>I'm looking at this commit https://github.com/danroth27/Net8BlazorWebAssembly/commit/44cf65ef602e89a5ec88b42d2f30f70d8f9fbda9 but I don't have a Host.razor in my app....

You need to add the Host.razor file to and copy over the content from index.html. Then make the changes to the content as shown in https://github.com/danroth27/Net8BlazorWebAssembly/commit/44cf65ef602e89a5ec88b42d2f30f70d8f9fbda9

**Comment by Webreaper** [comment]
Thanks, appreciate it. Will give it a go!
